create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  image_url text,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.products enable row level security;

create policy "Public can read categories"
on public.categories for select
to anon, authenticated
using (true);

create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);

create policy "Authenticated users can manage categories"
on public.categories for all
to authenticated
using (true)
with check (true);

create policy "Authenticated users can manage products"
on public.products for all
to authenticated
using (true)
with check (true);

insert into public.categories (name)
values ('Напитки'), ('Еда'), ('Коктейли')
on conflict (name) do nothing;

insert into public.products (name, description, price, image_url, category_id)
select
  'Blue Lagoon',
  'Освежающий цитрусовый коктейль с яркой бассейной подачей.',
  95,
  'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=900&q=80',
  id
from public.categories
where name = 'Коктейли'
on conflict do nothing;

insert into public.products (name, description, price, image_url, category_id)
select
  'Aqua Lemonade',
  'Домашний лимонад с мятой, лаймом и холодной содовой.',
  65,
  'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=900&q=80',
  id
from public.categories
where name = 'Напитки'
on conflict do nothing;

insert into public.products (name, description, price, image_url, category_id)
select
  'Pool Club Sandwich',
  'Легкий сэндвич с курицей, свежими овощами и фирменным соусом.',
  120,
  'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80',
  id
from public.categories
where name = 'Еда'
on conflict do nothing;
